<a href="https://colab.research.google.com/github/snfruby/CS114.K21/blob/master/Term_Document.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import requests
from bs4 import BeautifulSoup
import numpy as np
import glob
import re
import os

In [ ]:
import pandas as pd
import io
df = pd.read_excel('vnexpress-Data.xlsx', index_col=0)

In [ ]:
df

data  ... category
0     Kiến nghị lùi thời điểm lắp camera trên xe vận...  ...  thoi-su
1        Hiện trạng lún, nứt ở Bảo tàng Mỹ thuật TP HCM  ...  thoi-su
2     Hà Nội đề xuất làm tuyến đường sắt hơn 65.000 ...  ...  thoi-su
3       TP HCM xóa 'nút cổ chai' trên nhiều tuyến đường  ...  thoi-su
4                              6 người chết do bão Noul  ...  thoi-su
...                                                 ...  ...      ...
6629  Chủ nhân chăm sóc chim lúc mới nở đến khi trưở...  ...      hai
6630                   Hai 'nữ quái' trộm chậu rau húng  ...      hai
6631                                Tài xế khổ sở đỗ xe  ...      hai
6632  Võ sĩ 'dập mông' vì tung cước theo phong cách ...  ...      hai
6633        Tại sao ấm nước của công chúa út sôi trước?  ...      hai

[6634 rows x 4 columns]

In [ ]:
URL = df['url'].tolist()
category = df['category'].tolist()
print(len(category))

6634


In [ ]:
# lấy dữ liệu url với thể loại : thể thao
url_thethao=[]
for i in range(len(category)):
  if category[i]=='the-thao':
    url_thethao.append(URL[i])
len(url_thethao)

739

In [ ]:
# cào thử 5 url , đồng thời tạo file.txt sau đó đưa nội  dung vào bên trong
data=[]
k=0
for x in url_thethao[0:5]:
  print(x)
  r1 = requests.get(x)
  coverpage = r1.content
  soup1 = BeautifulSoup(coverpage, 'html5lib')
  coverpage_news = soup1.find_all("p")
  for i in coverpage_news:
    data.append(i.get_text())
  print(data)
  f= open("file"+str(k)+'.txt',"w+")
  with open('/content/file'+str(k)+'.txt', 'w') as writefile:
      for y in range(len(data)):
        writefile.write(data[y])
  k=str(int(k)+1)
  data.clear()


https://vnexpress.net/mourinho-cuop-loi-son-heung-min-de-ca-ngoi-kane-4165089.html
['Son Heung-min đang trả lời phỏng vấn sau khi lập poker ở Ngoại hạng Anh hôm 20/9, bất thình lình HLV Jose Mourinho chen vào và nói rằng Harry Kane mới là cầu thủ hay nhất.', 'Son được kênh BBC phỏng vấn sau chiến thắng 5-2 ở vòng 2 Ngoại hạng Anh trên sân của Southampton. Trận này, tiền đạo người Hàn Quốc ghi bốn bàn và được bình chọn là "Cầu thủ hay nhất". Toàn bộ các bàn thắng đó đều do Harry Kane kiến tạo. Anh cũng đồng thời là tác giả bàn còn lại của Tottenham.', 'Trong lúc Son đang lắng nghe câu hỏi, Jose Mourinho bỗng ghé đầu vào rồi nói "Cầu thủ hay nhất trận, Harry Kane".', 'Ông sau đó vỗ vai Son và rời đi, trong lúc cậu học trò cười gượng gạo.', 'Mourinho bất ngờ chen ngang buổi phỏng vấn sau trận của Son. Ảnh: BBC.', 'Phóng viên của BBC lập tức hỏi Son: "Nếu HLV trưởng đã nói như thế, anh có lý gì để tranh luận không?".', '"Tôi sẽ nói rằng Harry là cầu thủ hay nhất trận, bởi vì anh ấy ghi một

In [ ]:
Name=[]
file_paths = glob.glob("/content/*.txt")
lst_contents = []
dictionary = set()
for file_path in file_paths:
    f = open(file_path, 'r')
    str = f.read()
    # lst_contents.append(str)
    words = str.replace('"', '').replace('.', '').replace("'","").split()
    Name.append(os.path.splitext(file_path)[0][9:])
  

    
    words = set(words)
    lst_contents.append(words)
    dictionary.update(words)
    #print(words)
    #print ('Noi dung file cua ban la:\n', str)
print('Tap cac tu: ', dictionary)
dictionary = list(dictionary)


Tap cac tu:  {'hoạch', 'ngon', 'một,', 'Slam', 'Dybala', 'Sampras', 'luận', 'kém', 'khi', 'hỏi', 'đúng,', 'tuyệt', 'vạch', 'cãi', 'thấy', 'phối', 'theo', 'ghi', 'trưởng', 'đồng', 'Thành', 'này,', 'hồi', 'lưới', 'ba', 'lỡ', 'lên', '287', 'dẫn', 'tạo,', 'Rafael', 'vấn', 'Vắng', 'đều', 'kết,', 'trò', 'Trận', 'các', 'ngại', 'cáo,', 'xếp', 'đã', 'Vua', 'kịp', 'quyết', 'đáp', 'An', 'hỏi,', 'sự', 'sáu', 'RonaldoHoàng', 'hội', 'tĩnh,', 'sao', 'lắng', 'Chỉ', 'Liverpool', 'Watford', 'nỗ', 'Higuain,', 'anh', 'nhau,', 'Romario', 'hảoTheo', 'đồ', 'xảy', 'nayDjokovic', '1931-1956Do', 'hiệu', 'cản', 'tuần', 'tám', 'lý', 'ngữ', 'sức', 'giữa', 'trước,', 'Son', 'KaneÔng', 'Gareth', 'như', 'trẻ', 'nhấtSon', 'bên', 'Tour,', 'bóngTôi', '21/9*Djokovic', 'Pete', 'tới', 'luôn', 'Southampton', 'trí', 'hảo', 'cắm', 'cơ', 'bằng', 'Schwartzman:', 'cuối', 'công', 'Owen,', 'đấuKane', 'Họ', 'tức', 'ký', 'nó', 'phủ', 'tháng', 'giữ', 'cáoDjokovic', 'thình', 'Andrea', 'có', '98', 'mỗi', 'Serrgio', 'nói', '-', 'ngoài', 

In [ ]:
term_doc = np.zeros((len(dictionary), len(file_paths)))
print(term_doc)
print('Kich thuoc ma tran: ', term_doc.shape)
for k,word in enumerate(dictionary):
    for i,content in enumerate(lst_contents):
        if word in content:
            term_doc[k,i] = 1
            #print(word,"    ",content)
print(term_doc)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Kich thuoc ma tran:  (685, 5)
[[0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 ...
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


In [ ]:
query = 'NOT "Dybala" AND NOT "Sampras" OR NOT "khi" XOR NOT "Slam"' 
query_words = re.findall('"(\w+)"', query)
print(query_words)

['Dybala', 'Sampras', 'khi', 'Slam']


In [ ]:
array=[]

In [ ]:
for query_word in query_words:
    # tra vi tri cua query_word trong dictionary
    try:
        k = dictionary.index(query_word)
        word_vec = term_doc[k,:]
        print('Vector bieu dien cua ', query_word, ' la: ', word_vec)
        array.append(word_vec)
    except:
        pass


Vector bieu dien cua  Dybala  la:  [0. 1. 0. 0. 0.]
Vector bieu dien cua  Sampras  la:  [0. 0. 0. 0. 1.]
Vector bieu dien cua  khi  la:  [1. 1. 1. 1. 1.]
Vector bieu dien cua  Slam  la:  [0. 0. 0. 0. 1.]


In [ ]:
boolean = re.findall('(\w+) ',query)
boolean

['NOT', 'AND', 'NOT', 'OR', 'NOT', 'XOR', 'NOT']

In [ ]:
# xử lý tất cả những trường hợp NOT trước
count = 0
for i in range(len(boolean)):
  if boolean[i]=='NOT':
    array[i-count]=np.logical_not(array[i-count])
    count+=1
print(array)

for i in range(len(boolean)):
  if 'NOT' in boolean:
    boolean.remove('NOT')
print(boolean)


[array([ True, False,  True,  True,  True]), array([ True,  True,  True,  True, False]), array([False, False, False, False, False]), array([ True,  True,  True,  True, False])]
['AND', 'OR', 'XOR']


In [ ]:
array

[array([ True, False,  True,  True,  True]),
 array([ True,  True,  True,  True, False]),
 array([False, False, False, False, False]),
 array([ True,  True,  True,  True, False])]

In [ ]:
# xử lý các trường hợp AND OR XOR => kết quả cuối cùng
temp=array[0]
for i in range(len(boolean)):
  if boolean[i]=='AND':
    temp= np.logical_and(temp,array[i+1])
  if boolean[i]=='OR':
    temp= np.logical_or(temp,array[i+1])
  if boolean[i]=='XOR':
    temp= np.logical_xor(temp,array[i+1])
  print(temp)
  

[ True False  True  True False]
[ True False  True  True False]
[False  True False False False]


In [ ]:
temp = [1 if x==True else 0 for x in temp]
temp

[0, 1, 0, 0, 0]

In [ ]:
for i in range(len(Name)):
  if temp[i] ==1:
    print('ket qua xuat hien o',Name[i])

ket qua xuat hien o file3
